### ISSUE TITLE
com.sun.xml.internal import

### ISSUE THREAD

**Issue by istais** [lorisdanto/symbolicautomata#14]
Hello,

Do you need the [com.sun.xml.internal.bind.annotation.XmlLocation](https://github.com/lorisdanto/symbolicautomata/blob/5149243f24b88b5b96045e45ddb627e4516d1350/SVPAlib/src/theory/intervals/UnaryCharIntervalSolver.java#L17) import at UnaryCharIntervalSolver.java?

It creates a dependency issue in my platform. From what I read, a Java program that directly calls into [sun.* packages](http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html) is not guaranteed to work on all Java-compatible platforms, since the sun.* packages are not part of the supported, public interface. 

BTW, I am not sure if com.sun.* is the same with sun.*, Maybe this is not an issue for the com.sun.* I think they are different, but I still have a strange dependency issue

`
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project SVPAlib: Compilation failure
[ERROR] .../SVPAlib/src/theory/intervals/UnaryCharIntervalSolver.java:[17,44] package com.sun.xml.internal.bind.annotation does not exist
`

**Comment by lorisdanto** [comment]
I actually did the edit. I see something else is giving troubles from command line. I'm investigating.

THanks for the report

**Comment by lorisdanto** [comment]
I fixed another dependency and I removed some nonsense unit tests that were
put there by mistake.

Now it should all work.
