### ISSUE TITLE
Problem I meet some like \u000 \uffff，these seem likes error ?

### ISSUE THREAD

**Issue by JiCoM** [lorisdanto/symbolicautomata#24]
Hello，when I use your Instuments,I have a problem.\
String[] reBenchmarks = "(a|c|f|g|w|h|y|i|x|d)(a|c|f|g|w|h|y|i|x|d)(a|c|f|g|w|h|y|i|x|d)(a|c|f|g|w|h|y|i|x|d)(a|c|f|g|w|h|y|i|x|d)(a|c|f|g|w|h|y|i|x|d)",

strange data follows:
S: 0 -[\u0000-`b-ce-\uffff]-> 5
S: 0 -[d]-> 1
S: 0 -[a]-> 2
S: 1 -[e]-> 3
S: 1 -[\u0000-df-\uffff]-> 5
S: 2 -[\u0000-ac-\uffff]-> 5
S: 2 -[b]-> 4
S: 3 -[\u0000-\uffff]-> 5
S: 4 -[c]-> 3
S: 4 -[\u0000-bd-\uffff]-> 5
S: 5 -[\u0000-\uffff]-> 5

**Comment by lorisdanto** [comment]
Hi, I'm not sure what problem you are referring to. The line you posted does not seem to typecheck.
Can you post the piece of code you are running and what output you get?
