### ISSUE TITLE
Can I use the symbolic automata for Modeling check?Have some theories for guide?

### ISSUE THREAD

**Issue by JiCoM** [lorisdanto/symbolicautomata#25]
Hello, I want use this model for Modeling Check, I don't konw how can it do this job?
And have some examples for symbolic automata to show how it work ,compare to DFA?

**Comment by lorisdanto** [comment]
Hi, this file contains several examples of how one can create a symbolic automaton over the ASCII alphabet https://github.com/lorisdanto/symbolicautomata/blob/master/TestSVPA/src/test/SFA/SFAUnitTest.java
Let me know if this is what you are looking for.

**Comment by JiCoM** [comment]
My research is about CPS Modeling check, I think about  can I use the SFA in modeling check ,like used DFA before ,The verification of SFA have some research?

**Comment by lorisdanto** [comment]
There is indeed a lot of research.
This page contains many papers on the topic: http://pages.cs.wisc.edu/~loris/symbolicautomata.html
I recommend starting with this one: http://pages.cs.wisc.edu/~loris/papers/cav17-tutorial

**Comment by JiCoM** [comment]
Thank you!
